version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis_queue
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - proznanie_net

volumes:
  redis_data:

networks:
  proznanie_net:
    driver: bridge