version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis_queue
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - proznanie_net
    environment:
      - REDIS_PASSWORD=fjskfasng34fsd
    deploy:
      resources:
        limits:
          memory: 512M

volumes:
  redis_data:

networks:
  proznanie_net:
    name: proznanie_net
    driver: bridge