version: '3.8'  # Указываем версию для совместимости

services:
  redis:
    image: redis:latest
    container_name: redis_queue
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - proznanie_net
    deploy:
      resources:
        limits:
          memory: 512M  # Ограничение памяти остается

volumes:
  redis_data:

networks:
  proznanie_net:
    name: proznanie_net
    driver: bridge